# Form implementation generated from reading ui file 'add_company.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_company_widget(object):
    def setupUi(self, add_company_widget):
        add_company_widget.setObjectName("add_company_widget")
        add_company_widget.resize(445, 91)
        add_company_widget.setStyleSheet("QWidget {\n"
"    background-color: #fff;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(add_company_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel = BodyLabel(parent=add_company_widget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout.addWidget(self.BodyLabel)
        self.line_company_name = LineEdit(parent=add_company_widget)
        self.line_company_name.setObjectName("line_company_name")
        self.horizontalLayout.addWidget(self.line_company_name)
        self.btn_add_company_name = PrimaryPushButton(parent=add_company_widget)
        self.btn_add_company_name.setObjectName("btn_add_company_name")
        self.horizontalLayout.addWidget(self.btn_add_company_name)

        self.retranslateUi(add_company_widget)
        QtCore.QMetaObject.connectSlotsByName(add_company_widget)

    def retranslateUi(self, add_company_widget):
        _translate = QtCore.QCoreApplication.translate
        add_company_widget.setWindowTitle(_translate("add_company_widget", "添加公司"))
        self.BodyLabel.setText(_translate("add_company_widget", "公司名:"))
        self.btn_add_company_name.setText(_translate("add_company_widget", "确定"))
from qfluentwidgets import BodyLabel, LineEdit, PrimaryPushButton
