# Form implementation generated from reading ui file 'file_item.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_file_item(object):
    def setupUi(self, file_item):
        file_item.setObjectName("file_item")
        file_item.resize(510, 32)
        file_item.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(file_item)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_file_name = QtWidgets.QLabel(parent=file_item)
        self.label_file_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_file_name.setText("")
        self.label_file_name.setObjectName("label_file_name")
        self.horizontalLayout.addWidget(self.label_file_name)
        self.combo_file_type = ComboBox(parent=file_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_file_type.sizePolicy().hasHeightForWidth())
        self.combo_file_type.setSizePolicy(sizePolicy)
        self.combo_file_type.setMinimumSize(QtCore.QSize(120, 0))
        self.combo_file_type.setMaximumSize(QtCore.QSize(120, 16777215))
        self.combo_file_type.setStyleSheet("ComboBox {\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    padding: 5px 31px 6px 11px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\'; */\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    text-align: left;\n"
"}\n"
"\n"
"ComboBox:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"ComboBox:pressed {\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"}\n"
"\n"
"ComboBox:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"")
        self.combo_file_type.setText("")
        self.combo_file_type.setCheckable(False)
        self.combo_file_type.setFlat(False)
        self.combo_file_type.setObjectName("combo_file_type")
        self.horizontalLayout.addWidget(self.combo_file_type)

        self.retranslateUi(file_item)
        QtCore.QMetaObject.connectSlotsByName(file_item)

    def retranslateUi(self, file_item):
        _translate = QtCore.QCoreApplication.translate
        file_item.setWindowTitle(_translate("file_item", "文件行"))
from qfluentwidgets import ComboBox
