# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1052, 65)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.BodyLabel_3 = BodyLabel(parent=Form)
        self.BodyLabel_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.gridLayout.addWidget(self.BodyLabel_3, 0, 3, 1, 1)
        self.BodyLabel_4 = BodyLabel(parent=Form)
        self.BodyLabel_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.gridLayout.addWidget(self.BodyLabel_4, 0, 7, 1, 1)
        self.BodyLabel_5 = BodyLabel(parent=Form)
        self.BodyLabel_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_5.setObjectName("BodyLabel_5")
        self.gridLayout.addWidget(self.BodyLabel_5, 0, 8, 1, 1)
        self.BodyLabel = BodyLabel(parent=Form)
        self.BodyLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.BodyLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 1, 1, 1)
        self.BodyLabel_8 = BodyLabel(parent=Form)
        self.BodyLabel_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_8.setObjectName("BodyLabel_8")
        self.gridLayout.addWidget(self.BodyLabel_8, 0, 4, 1, 1)
        self.BodyLabel_7 = BodyLabel(parent=Form)
        self.BodyLabel_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_7.setObjectName("BodyLabel_7")
        self.gridLayout.addWidget(self.BodyLabel_7, 0, 5, 1, 1)
        self.BodyLabel_2 = BodyLabel(parent=Form)
        self.BodyLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout.addWidget(self.BodyLabel_2, 0, 0, 1, 1)
        self.BodyLabel_6 = BodyLabel(parent=Form)
        self.BodyLabel_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_6.setObjectName("BodyLabel_6")
        self.gridLayout.addWidget(self.BodyLabel_6, 0, 9, 1, 1)
        self.BodyLabel_9 = BodyLabel(parent=Form)
        self.BodyLabel_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_9.setObjectName("BodyLabel_9")
        self.gridLayout.addWidget(self.BodyLabel_9, 1, 0, 1, 1)
        self.BodyLabel_10 = BodyLabel(parent=Form)
        self.BodyLabel_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_10.setObjectName("BodyLabel_10")
        self.gridLayout.addWidget(self.BodyLabel_10, 1, 1, 1, 1)
        self.BodyLabel_11 = BodyLabel(parent=Form)
        self.BodyLabel_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BodyLabel_11.setObjectName("BodyLabel_11")
        self.gridLayout.addWidget(self.BodyLabel_11, 1, 3, 1, 1)
        self.CheckBox = CheckBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckBox.sizePolicy().hasHeightForWidth())
        self.CheckBox.setSizePolicy(sizePolicy)
        self.CheckBox.setMinimumSize(QtCore.QSize(38, 22))
        self.CheckBox.setMaximumSize(QtCore.QSize(22, 16777215))
        self.CheckBox.setStyleSheet("CheckBox {\n"
"    color: black;\n"
"    font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\';\n"
"    spacing: 8px;\n"
"    min-width: 28px;\n"
"    min-height: 22px;\n"
"    outline: none;\n"
"    margin-left: 10px;\n"
"}\n"
"\n"
"CheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(0, 0, 0, 0.48);\n"
"    background-color: rgba(0, 0, 0, 0.022);\n"
"}\n"
"\n"
"CheckBox::indicator:hover {\n"
"    border: 1px solid rgba(0, 0, 0, 0.56);\n"
"    background-color: rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"CheckBox::indicator:pressed {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: rgba(0, 0, 0, 0.12);\n"
"}\n"
"\n"
"CheckBox::indicator:checked,\n"
"CheckBox::indicator:indeterminate {\n"
"    border: 1px solid #009faa;\n"
"    background-color: #009faa;\n"
"}\n"
"\n"
"\n"
"CheckBox::indicator:checked:hover,\n"
"CheckBox::indicator:indeterminate:hover {\n"
"    border: 1px solid #00a7b3;\n"
"    background-color: #00a7b3;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:pressed,\n"
"CheckBox::indicator:indeterminate:pressed {\n"
"    border: 1px solid #3eabb3;\n"
"    background-color: #3eabb3;\n"
"}\n"
"\n"
"CheckBox:disabled {\n"
"    color: rgba(0, 0, 0, 110);\n"
"}\n"
"\n"
"CheckBox::indicator:disabled {\n"
"    border: 1px solid rgba(0, 0, 0, 0.27);\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"CheckBox::indicator:checked:disabled,\n"
"CheckBox::indicator:indeterminate:disabled {\n"
"    border: 1px solid rgb(199, 199, 199);\n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        self.CheckBox.setText("")
        self.CheckBox.setObjectName("CheckBox")
        self.gridLayout.addWidget(self.CheckBox, 1, 5, 1, 1)
        self.BodyLabel_12 = BodyLabel(parent=Form)
        self.BodyLabel_12.setObjectName("BodyLabel_12")
        self.gridLayout.addWidget(self.BodyLabel_12, 1, 9, 1, 1)
        self.BodyLabel_3.setBuddy(Form.line_type_id)
        self.BodyLabel_4.setBuddy(Form.line_time_col)
        self.BodyLabel_5.setBuddy(Form.line_time_format)
        self.BodyLabel.setBuddy(Form.line_data_config_name)
        self.BodyLabel_8.setBuddy(Form.line_sheet)
        self.BodyLabel_2.setBuddy(Form.line_channel_id)
        self.BodyLabel_6.setBuddy(Form.line_customer_col)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BodyLabel_3.setText(_translate("Form", "类型标识:"))
        self.BodyLabel_4.setText(_translate("Form", "时间列 [表字段名]:"))
        self.BodyLabel_5.setText(_translate("Form", "时间格式:"))
        self.BodyLabel.setText(_translate("Form", "配置名:"))
        self.BodyLabel_8.setText(_translate("Form", "Sheet表名:"))
        self.BodyLabel_7.setText(_translate("Form", "有时间列:"))
        self.BodyLabel_2.setText(_translate("Form", "渠道标识:"))
        self.BodyLabel_6.setText(_translate("Form", "客户名列 [表字段名]:"))
        self.BodyLabel_9.setText(_translate("Form", "Body label"))
        self.BodyLabel_10.setText(_translate("Form", "Body label"))
        self.BodyLabel_11.setText(_translate("Form", "Body label"))
        self.BodyLabel_12.setText(_translate("Form", "Body label大大实打实大苏打撒大苏打实打实的阿三大苏打实打实啊倒萨啊大苏打阿达爱上阿松大阿达爱上的s"))
from qfluentwidgets import BodyLabel, CheckBox
